# クラスにコメントを残さない
Documentation:
  Enabled: false

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 128

Metrics/BlockLength:
  Enabled: false

TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

# frozen string literal を付けていなくても警告しない
Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - config/**/*
    - db/migrate/*
    - Gemfile
    - Rakefile
