# クラスにコメントを残さない
Documentation:
  Enabled: false

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 128

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - config/**/*
    - db/migrate/*
    - Gemfile
    - Rakefile
