mailer:
  address: 'smtp.gmail.com'
  port: 587
  domain: 'gmail.com'
  user_name: 'freezer53000@gmail.com'
  password: 'fbnvyyksmsfwdnau'
  authentication: 'plain'
  enable_starttls_auto: true
  from: 'freezer53000@gmail.com'
