mailer:
  address: 'smtp.gmail.com'
  port: 587
  domain: 'foo@example.com'
  user_name: 'hoge@example.com'
  password: 'hogehoge'
  authentication: 'plain'
  enable_starttls_auto: true
  from: 'hoge@example.com'
